import type { Metadata } from 'next'
import { Roboto_Mono } from 'next/font/google'
import './globals.css'

const Robot = Roboto_Mono({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'UI Mockup',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={Robot.className}>
        {children}
      </body>
    </html>
  )
}
